<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>CopyTool.Bench</RootNamespace>
    <AssemblyName>CopyTool.Bench</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CopyTool.Core/CopyTool.Core.csproj" />
  </ItemGroup>
</Project>
